# Generated by Django 2.0.7 on 2018-10-24 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181024_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 24, 16, 6, 32, 449438, tzinfo=utc)),
        ),
    ]
