# Generated by Django 2.1.2 on 2018-10-27 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20181025_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 16, 8, 57, 526906, tzinfo=utc)),
        ),
    ]
