# Generated by Django 2.1.2 on 2018-11-07 16:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20181105_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 16, 5, 30, 540312, tzinfo=utc)),
        ),
    ]
