# Generated by Django 2.1.2 on 2018-11-07 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20181108_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 16, 19, 14, 974510, tzinfo=utc)),
        ),
    ]
