# Generated by Django 2.1.2 on 2018-11-07 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20181108_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 7, 16, 21, 48, 151310, tzinfo=utc)),
        ),
    ]
