# Generated by Django 2.1.2 on 2018-11-08 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20181108_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 15, 6, 9, 921499, tzinfo=utc)),
        ),
    ]
