# Generated by Django 2.1.2 on 2018-11-09 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20181108_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 16, 55, 23, 110846, tzinfo=utc)),
        ),
    ]
