# Generated by Django 2.1.2 on 2018-11-09 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20181110_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 9, 20, 47, 28, 1997, tzinfo=utc)),
        ),
    ]
